[package]
name = "profile"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "profile"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
profile_integrity = { workspace = true }
